apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-m-pvc
spec:
  selector:
    matchLabels:
      app: multi
  template:
    metadata:
      labels:
        app: multi
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - name: volume-nfs
          mountPath: /input
      volumes:
      - name: volume-nfs
        persistentVolumeClaim:
          claimName: my-pvc
          
---               
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: nfs-csi
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
